Himalaya_treks_nepal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from django.views.defaults import page_not_found
from .views import handler500


admin.site.site_header = "Himalaya treks nepal"
admin.site.site_title = "Himalaya treks nepal"
admin.site.index_title = "Himalaya | admin"


urlpatterns = [
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps={
    'posts':PostSitemap,
}

app_name = 'blog'

urlpatterns = [
    path('', views.home_page , name='home' ),
    path('search/', views.SearchPostView.as_view() , name='search' ),
    path('posts/', views.PostListView.as_view() , name='posts' ),
    path('post/<slug>/', views.PostDetailView.as_view() , name='post_detail' ),
    path('socials/', views.SocialListView.as_view() , name='socials' ),
    path('social/<slug>/', views.SocialDetailView.as_view() , name='social_detail' ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('<slug>/', views.PostCategory.as_view() , name='posts_by_category' ),

]


pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about-us', views.about_us , name='about_us' ),
    path('contact-us', views.contact_us , name='contact_us' ),
    path('enquiry-success', views.success , name='success' ),
    path('why_with_us',views.why_with_us, name='why_with_us'),
    path('booking_form',views.booking_form,name='booking_form'),
    path('Booking',views.handle_booking,name='handle_booking'),
    path('Enquiry',views.handle_enquiry,name='handle_enquiry'),
    path('corona',views.corona,name='corona'),
    path('legal',views.legal,name='legal'),
    path('enquiry',views.enquiry,name='enquiry'),
    path('who_we_are',views.who_we_are, name='who_we_are'),
    # path('Enquiry',views.display_enquiry,name='display_enquiry'),
    path('booking_success', views.booking_success , name='booking_success' ),

]

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">


templates/base/footer.html
{% load static %}


<footer>
    <div class="container">
        <div class="row">
            <!--logo img footer-->
            <div class="col-sm-12 col-md-3 ">
                <div class="logo-footer">
                    <!--logo-->
                      <!--title footer -->
                    <ul class="footer-categories-list">
                      <img src="{% static 'img/navlogo.png' %}" style="padding-left: 2px; padding-bottom: 3px; clear: both;">
                      <h4 class="title-footer">We Accept</h4>
                      <img src="https://raw.githubusercontent.com/thulotechnology/useful/main/cards.png" height="40" width="100">
                     <br>
                      <h4 class="title-footer">Our Partner</h4>
                      <img src="https://raw.githubusercontent.com/himalayentreksnepal/himalayantrekspublic/main/in-partnership-with.png" height="40" width="100">
                    </ul>
                   
                </div>
            </div>
            <!--ENQUIRES items -->
            <div class="col-sm-12 col-md-4">
                <!--title footer -->
                <h2 class="title-footer">ABOUT US & ENQUIRIES</h2>
                <!--list -->
                <ul class="footer-categories-list">
                    <li class="categories-item"><a class="categories-link" href="{% url 'pages:about_us' %}#Contact">General</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/about/contact/">Contact Us</a></li>
                    <li class="categories-item"><a class="categories-link" href="/faqs/">FAQs</a></li>
                    <li class="categories-item"><a class="categories-link" href="{% url 'pages:about_us' %}">About Us</a></li>
                    <li class="categories-item"><a class="categories-link" href="/terms-and-conditions/">Terms & Conditions</a></li>
                </ul>
            </div>
            <div class="col-sm-12 col-md-4">
                <!--title footer -->
                <h2 class="title-footer">Some Famous Content</h2>
                <!--list -->
                <ul class="footer-categories-list">
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/everest-expedition/">Everest Expedition</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/annapurna-base-camp-trek/">Annapurna Base Camp Trek</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/upper-mustang-trek/">Upper Mustang Trek</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/jiri-everest-base-camp-trek/">Jiri Everest Base Camp Trek</a></li>
                </ul>
            </div>
        </div>
        <!--foooer down -->
        <div class="footer__down d-flex justify-content-between align-items-center flex-wrap">
            <div class="copy-right order-1"> 
                <!--copy footer-->
                <a class="copy-right-link mr-5 text-muted" style="font-size: 10px;">© Himalaya Treks Nepal 2021</a>
            </div>
            <!--social icons -->
            <div class="icon-social order-2">
                    <a href="https://www.instagram.com/himalayatreks.nepal/" target="_blank" style="font-size: 25px;"><i class="fab fa-instagram"></i></a>
                    <a href="https://www.facebook.com/himalayatreksnepal/" target="_blank" style="font-size: 25px;"><i class="fab fa-facebook"></i></a>
            </div>
       </div>
    </div>
</footer>

<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      xfbml            : true,
      version          : 'v10.0'
    });
  };

  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- Your Chat Plugin code -->
<div class="fb-customerchat"
  attribution="setup_tool"
  page_id="102410194629333">
</div>

templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/Headroom.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/popup_corona.js' %}"></script>
<script src="{% static 'js/ckeditor-responsive-images.js' %}"></script>


templates/base/navbar.html
{% load static %}
<header {% if header %}class="has__header" {% endif %}>
    <!-- Navbar -->
    <nav style="z-index:100000000;" class="{% if header %}not__background{% else %}has__background{% endif %} navbar navbar-expand-lg navbar-light {% if header %}position-fixed{% endif %}  headroom headroom--pinned">
        <div class="container">
            <!--logo nav-->
            <a class="navbar-brand" href="/"><img src="{% static 'img/navlogo.png' %}" class="logo-img wow rollIn" data-wow-duration='2s'></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <!--nav toggle -->
          <i class="fas fa-bars color-white toggle-menu"></i>
        </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <!--nav list -->
                <ul class="navbar-nav ">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'pages:about_us' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'pages:who_we_are' %}">Who we are</a>
                            <a class="dropdown-item" href="{% url 'pages:about_us' %}">Our Team</a>
                            <a class="dropdown-item" href="{% url 'pages:booking_form' %}">Booking</a>
                            <a class="dropdown-item" href="{% url 'pages:legal' %}">Legal Documents</a>
                            <a class="dropdown-item" href="{% url 'pages:why_with_us' %}">Why With Us</a>
                            <a class="dropdown-item" href="https://thimalayanepal.com/faqs/">FAQ</a>
                            <a class="dropdown-item" href="/terms-and-conditions/">Terms and Conditions</a>
                            <a class="dropdown-item" href="{% url 'pages:corona' %}">Corona Updates</a>
                        </div>
                    </li>


                    {% for c in categories %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.name }} </a>
                    </li>
                    {% endfor %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:enquiry' %}">Enquiry </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:posts' %}">Blog </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:socials' %}">Social  </a>
                    </li>

                </ul>
                <!--search box -->
                <ul class="navbar-nav ml-auto nav-flex-icons">
                    <li class="nav-item">
                        <form class="form-inline" action="{% url 'blog:search' %}" method="get">
                            <input style="width: 241px;" name='q' class="form-control mr-sm-2" type="search" placeholder="Search" value="{{ query }}" aria-label="Search">
                            <button class="button-primary" type="submit"><i class="fas fa-search"></i></button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>