Himalaya_treks_nepal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from django.views.defaults import page_not_found
from .views import handler500


admin.site.site_header = "Himalaya treks nepal"
admin.site.site_title = "Himalaya treks nepal"
admin.site.index_title = "Himalaya | admin"


urlpatterns = [
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps={
    'posts':PostSitemap,
}

app_name = 'blog'

urlpatterns = [
    path('', views.home_page , name='home' ),
    path('search/', views.SearchPostView.as_view() , name='search' ),
    path('posts/', views.PostListView.as_view() , name='posts' ),
    path('post/<slug>/', views.PostDetailView.as_view() , name='post_detail' ),
    path('socials/', views.SocialListView.as_view() , name='socials' ),
    path('social/<slug>/', views.SocialDetailView.as_view() , name='social_detail' ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('<slug>/', views.PostCategory.as_view() , name='posts_by_category' ),

]


pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about-us', views.about_us , name='about_us' ),
    path('contact-us', views.contact_us , name='contact_us' ),
    path('enquiry-success', views.success , name='success' ),
    path('why_with_us',views.why_with_us, name='why_with_us'),
    path('booking_form',views.booking_form,name='booking_form'),
    path('Booking',views.handle_booking,name='handle_booking'),
    path('Enquiry',views.handle_enquiry,name='handle_enquiry'),
    path('corona',views.corona,name='corona'),
    path('legal',views.legal,name='legal'),
    path('enquiry',views.enquiry,name='enquiry'),
    path('who_we_are',views.who_we_are, name='who_we_are'),
    # path('Enquiry',views.display_enquiry,name='display_enquiry'),
    path('booking_success', views.booking_success , name='booking_success' ),

]

templates/pages/about_us.html
{% extends 'base.html' %} {% load static %} {% block title %}About Us{% endblock %} {% block content %}

</header>


<!--<section class="text__about">-->
    <div class="container-md container-fluid mt-4">
        <!--title -->
        <div class="title-left text-left wow bounce" data-wow-duration='2s'>
            <h2>{{ about.first_title }} {% if user.is_authenticated and user.is_staff or user.is_superuser %}
                <a class="btn btn-info" href="{% url 'admin:pages_aboutuspage_change' about.id %}"> Edit about info <i class="far fa-edit"></i></a> {% endif %}
            </h2>
            {% if about.second_title %}
            <h4>{{ about.second_title }}</h4>
            {% endif %} {% comment %}
            <p class="text-justify">{{ about.content|safe|linebreaks }}</p> {% endcomment %}
            <!-- <p class="text-justify">HIMALAYA TREKS NEPAL Is Established Under Company Act 2006 Pursuant To Sub Section (1) Of Section 5 (Registration No 231501/076/077: Pan No:609692556). The Company Is Licensed By Tax Department Of Nepal As A Taxpayer, And By Central Bank Of Nepal As Foreign Currency Acceptable Company From Foreigners And Members Of National And International Tourism Umbrella Organizations. -->
        </div>
        <section class="our-team text-center" style="padding: 0px !important;">
            <div class="team">
                <div class="container" id="Team">
                    <h2 class="h1">Meet Our Awesome Team {% if user.is_authenticated and user.is_staff or user.is_superuser %} {% if members.count == 10 %}
                        <a class="btn btn-info" href="{% url 'admin:pages_member_changelist' %}">edit members <i class="far fa-edit"></i></a> {% else %}
                        <a class="btn btn-primary" href="{% url 'admin:pages_member_add' %}">add member <i class="far fa-plus-square"></i></a> {% endif %} {% endif %}
                    </h2>
                    <div class="row">
                        {% for member in members %} {% if forloop.counter == 20 or forloop.counter == 19 %}
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            {% else %}
                            <div class="col-lg-3 col-md-6 col-sm-6">
                                {% endif %}
                                <button type="button" class="btn btn-light" data-toggle="modal" data-target="#member{{member.id}}">
                                <div class="person">
                                <img class="imgCircle" src="{% if member.image %}{{ member.image.url }}{% else %}{% static 'img/member.png' %}{% endif %}" alt="{{member.name}}">
                                <h4 class="upper">{{member.name}}</h4>
                                    <p>
                                        {{member.role}}
                                    </p>
                                </div>
                                </button>
                            </div>
                            <div class="modal fade" id="member{{member.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content" style="border:3px blue solid">
                                        <div class="modal-header" style="border-bottom: 3px solid blue;">
                                            <h5 class="modal-title text-primary" id="exampleModalLongTitle" style="margin-left: 90px;">Mr.{{member.name}}&nbsp;({{member.role}})
                                            </h5>
                                            <button type="button btn-primary" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <div class="modal-body font-weight-lighter text-sm-center">
                                            <h5 class="border  border-sm rounded border-primary p-2"> About {{member.name}}</h5>
                                            <h6 style="text-align: justify" class="font-weight-light">{{member.about}}</h6>
                                        </div>
                                        <div class="modal-footer" style="border-top: 3px solid blue;">

                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
        </section>
        </div>
<!--        <div class="container" id="Contact" > -->
<!--            <div class="title-left text-left wow bounce" data-wow-duration='2s'>-->
<!--                <h2>Enquiry</h2>-->
<!--            </div>-->
<!--            <section class="text__about">-->
        <div class="container-fluid container-md" id="Contact" >
            <div class="title-left text-left wow bounce" data-wow-duration='2s'>
                <h2>Enquiry</h2>
            </div>
            <section class="form__section" style="padding: 0px !important;">
                    <form method="POST" action="{% url 'pages:handle_enquiry' %}" data-endpoint="{% url 'pages:handle_enquiry' %}" class=" justify-content-between flex-column flex-wrap align-item-center form__enquery">
                        {% csrf_token %}
                        <!--title --> 
                        <h2 class="name">Enquiry</h2>
                        <!--MESSAGE --> 
                        <textarea class="message" name="message" id="message" placeholder="Your Message"></textarea>
                        <p style="font-size: 18px;">Your Details</p>
                        <!--input container --> 
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" name="full_name" placeholder="full name" placeholder="full name" required>
                            <input class="email" type="email" name="email" id="email" placeholder="email" required>
                        </div>
                        <!--input container -->
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" id="country" name="country" placeholder="country">
                        </div>
                        <div class=" justify-content-between flex-wrap" >
                            <!--button  -->
                            <input class="code" type="number" name="phone" placeholder="Contact Number">
                            <div class="test">
                                <button class="btn button-primary"><i class="fas fa-chevron-right"></i> Submit Request</button>
                            </div>
                        </div>
                    </form>

            </section>
        </div>
        
    </div>  
  </section>
        </div>
    </div>
</section>



{% endblock %}

templates/pages/booking.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About Us{% endblock %}
{% block content %}

</header>


<section class="text__about">
        <div class="container" id="Contact" > 
            <div class="title-left text-left wow bounce" data-wow-duration='2s'>
                <h2>Enquiry</h2>
            </div>
            <section class="form__section" style="padding: 0px !important;">
                    <form method="POST" action="{% url 'pages:contact_us' %}" data-endpoint="{% url 'pages:contact_us' %}" class=" justify-content-between flex-column flex-wrap align-item-center form__enquery">
                        {% csrf_token %}
                        <!--title --> 
                        <h2 class="name">Booking</h2>
                        <!--MESSAGE --> 
                        <textarea class="message" name="message" id="message" placeholder="Your Message"></textarea>
                        <p style="font-size: 18px;">Your Details</p>
                        <!--input container --> 
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" name="full_name" placeholder="full name" placeholder="full name" required>
                            <input class="email" type="email" name="email" id="email" placeholder="email" required>
                        </div>
                        <input class="company" type="text" id="package" name="package" placeholder="Requested Package" required>
                        <!--input container -->
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" id="country" name="country" placeholder="country">
                        </div>
                        <div class=" justify-content-between flex-wrap" >
                            <!--button  -->
                            <input class="code" type="number" name="phone" placeholder="Contact Number">
                            <div class="test">
                                <button class="btn button-primary"><i class="fas fa-chevron-right"></i> Submit Request</button>
                            </div>
                        </div>
                    </form>

            </section>
        </div>
        
    </div>  
  </section>



{% endblock %}

templates/pages/booking_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Booking Form{% endblock %}
{% block content %}

</header>
<div class="container" id="Contact" > 
            <div class="title-left text-left wow bounce" data-wow-duration='2s'>
                <h2>Booking</h2>
            </div>
            <section class="form__section" style="padding: 0px !important;">
                    <form method="POST" action="{% url 'pages:handle_booking' %}" data-endpoint="{% url 'pages:handle_booking' %}" class=" justify-content-between flex-column flex-wrap align-item-center form__enquery">
                        {% csrf_token %}
                        <!--title --> 
                        <h2 class="name">Booking</h2>
                        <!--MESSAGE --> 
                        <textarea class="message" name="message" id="message" placeholder="Your Message"></textarea>
                        <p style="font-size: 18px;">Your Details</p>
                        <!--input container --> 
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" name="full_name" placeholder="full name" placeholder="full name" required>
                            <input class="email" type="email" name="email" id="email" placeholder="email" required>
                        </div>
                        <input class="company" type="text" id="package" name="package" placeholder="Requested Package" required>
                        <!--input container -->
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" id="country" name="country" placeholder="country">
                        </div>
                        <div class=" justify-content-between flex-wrap" >
                            <!--button  -->
                            <input class="code" type="number" name="phone" placeholder="Contact Number">
                            <div class="test">
                                <button class="btn button-primary"><i class="fas fa-chevron-right"></i> Request Booking</button>
                            </div>
                        </div>
                    </form>

            </section>
        </div>
        
    </div>  
  </section>
  {% endblock %}


templates/pages/booking_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Thank You{% endblock %}
{% block content %}


</header>


<div class="container" style="height: 300px;">
  {% if messages %}
  <ul class="messages list-unstyled mt-5">
      {% for message in messages %}
      <li class="alert {{ message.tags }} messages alert-dismissible fade show" role="alert">
        {% if message.tags == 'alert-danger' %}
        <i class="fas fa-exclamation-circle"></i>
        {% else %}
        <i class="fas fa-check-circle"></i>
        {% endif %}
        {{ message }}
        <button type="button" class="close" data-dismiss='alert' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </li>
      <hr>
      <a href="{% url 'blog:home' %}" class="btn btn-info">Back to Home</a>
      {% endfor %}
  </ul>
  {% else %}
  <ul class="list-unstyled mt-5 text-center">
      <li class="alert alert-success ">Thank you for your booking, we will get back to you as soon as possible.</li>
      <a href="{% url 'blog:home' %}" class="btn btn-info">Back to Home</a>
  </ul>
  {% endif %}

</div>

{% endblock %}

templates/pages/contact_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact Us{% endblock %}
{% block content %}

</header>
<h2>Our Details </h2>



{% endblock %}

templates/pages/enquiry.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Enquiry{% endblock %}
{% block content %}

</header>


<!--<section class="text__about">-->
        <div class="container-fluid container-md" id="Contact" >
            <div class="title-left text-left wow bounce" data-wow-duration='2s'>
                <h2 class="mt-4">Enquiry</h2>
            </div>
            <section class="form__section" style="padding: 0px !important;">
                    <form method="POST" action="{% url 'pages:handle_enquiry' %}" data-endpoint="{% url 'pages:handle_enquiry' %}" class=" justify-content-between flex-column flex-wrap align-item-center form__enquery">
                        {% csrf_token %}
                        <!--title --> 
                        <h2 class="name">Enquiry</h2>
                        <!--MESSAGE --> 
                        <textarea class="message" name="message" id="message" placeholder="Your Message"></textarea>
                        <p style="font-size: 18px;">Your Details</p>
                        <!--input container --> 
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" name="full_name" placeholder="full name" placeholder="full name" required>
                            <input class="email" type="email" name="email" id="email" placeholder="email" required>
                        </div>
                        <!--input container -->
                        <div class=" justify-content-order align-item-start form__name">
                            <input type="text" class="firstname" id="country" name="country" placeholder="country">
                        </div>
                        <div class=" justify-content-between flex-wrap" >
                            <!--button  -->
                            <input class="code" type="number" name="phone" placeholder="Contact Number">
                            <div class="test">
                                <button class="btn button-primary"><i class="fas fa-chevron-right"></i> Submit Request</button>
                            </div>
                        </div>
                    </form>

            </section>
        </div>
        
    </div>  
  </section>



{% endblock %}

templates/pages/footer.html
{% load static %}


<footer>
    <div class="container">
        <div class="row ">
            <!--logo img footer-->
            <div class="col-sm-12 col-md-3 ">
                <div class="logo-footer">
                    <!--logo-->
                      <!--title footer -->
                
                    <ul class="footer-categories-list">
                      <img src="{% static 'img/navlogo.png' %}" style="padding-left: 2px; padding-bottom: 3px; clear: both; margin-top:-25px;">
                      <h2 class="title-footer">We Accept</h2>
                      <img src="https://raw.githubusercontent.com/thulotechnology/useful/main/cards.png" height="60" width="100"><br><br>
                    </ul> 
                </div>
            </div>
           <!--ENQUIRES items -->
            <div class="col-sm-12 col-md-3">
                <!--title footer -->
                <h2 class="title-footer">ABOUT US & ENQUIRIES</h2>
                <!--list -->
                <ul class="footer-categories-list">
                    <li class="categories-item"><a class="categories-link" href="{% url 'pages:about_us' %}#Contact">General</a></li>
                    <li class="categories-item"><a class="categories-link" href="/faqs/">FAQs</a></li>
                    <li class="categories-item"><a class="categories-link" href="{% url 'pages:about_us' %}">About Us</a></li>
                    <li class="categories-item"><a class="categories-link" href="/terms-and-conditions/">Terms & Conditions</a></li>
                </ul>
            </div>
            <div class="col-sm-16 col-md-2">
                <!--title footer -->
                <h2 class="title-footer">Contact Us</h2>
                <!--list -->
                <ul class="footer-categories-list">
                    <li class="categories-item"><a class="categories-link" href="#">Facebook<span class="icon-facebook"></span></a></li>
                    <li class="categories-item"><a class="categories-link" href="#">Email</a></li>
                    <li class="categories-item"><a class="categories-link" href="">Website</a></li>
                    <li class="categories-item"><a class="categories-link" href="#">Telephone</a></li>
            </div>
            <div class="col-sm-12 col-md-3">
                <!--title footer -->
                <h2 class="title-footer">Some Famous Content</h2>
                <!--list -->
                <ul class="footer-categories-list">
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/everest-expedition/">Everest Expedition</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/annapurna-base-camp-trek/">Annapurna Base Camp Trek</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/upper-mustang-trek/">Upper Mustang Trek</a></li>
                    <li class="categories-item"><a class="categories-link" href="https://thimalayanepal.com/post/jiri-everest-base-camp-trek/">Jiri Everest Base Camp Trek</a></li>
                </ul>
            </div>
        </div>
        <div class="text-center">
                <h2 class="title-footer">WE ARE ASSOCIATED WITH</h2><br>
                <img src="https://raw.githubusercontent.com/thulotechnology/useful/main/cards.png" height="100" width="50%" >
        </div>
        <!--foooer down -->
        <div class="footer__down d-flex justify-content-between align-items-center flex-wrap">
            <div class="copy-right order-1"> 
                <!--copy footer-->
                <a class="copy-right-link mr-5 text-muted" style="font-size: 10px;">© Himalaya Treks Nepal 2021</a>
            </div>
            <!--social icons -->
            <div class="icon-social order-2">
                    <a href="https://www.instagram.com/himalayatreks.nepal/" target="_blank" style="font-size: 25px;"><i class="fab fa-instagram"></i></a>
                    <a href="https://www.facebook.com/himalayatreksnepal/" target="_blank" style="font-size: 25px;"><i class="fab fa-facebook"></i></a>
            </div>
       </div>
</footer>

templates/pages/socials_info.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Social Works{% endblock %}
{% block content %}

    <!--img and the img src is in style html -->
        <img style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.5)) , url({% if social_header.image %}{{ social_header.image.url }}{% else %}{% static 'img/default.jpg' %}{% endif %})" class="img-header">
        <div class="container">
            <!--box text -->
            <div class="box__text">
                <h1 class="hero__text wow fadeInDown" data-wow-duration="2s" >
                    {% if user.is_authenticated and user.is_staff  or user.is_superuser %}
                    <a class="btn btn-info" href="{% url 'admin:pages_socialheader_change' social_header.id %}"> Edit this header <i class="far fa-edit"></i></a>
                    {% endif %} 
                    <span>{{ social_header.title }}</span>{{ social_header.header_title }}</h1>
                <!--button-->
                <a class="button__circle wow fadeInDown discover" data-wow-duration="3s" ><i class="fas fa-arrow-down"></i>Learn More </a>
            </div>
        </div>
  </header> 
{% comment %} <div class="container">
    <!--box text -->
    <div class="box__text">
        <h1 class="hero__text wow fadeInDown" data-wow-duration="2s" >
            {% if user.is_authenticated and user.is_staff  or user.is_superuser %}
            <a class="btn btn-info" href="{% url 'admin:pages_homeheader_change' home_header.id %}"> Edit this header <i class="far fa-edit"></i></a>
            {% endif %} 
            <span>{{ home_header.title }}</span> {{ home_header.header_title }}</h1>
        <!--button-->
        <a style="color: white;" class="button__circle wow fadeInDown card-link" href="https://thimalayanepal.com/post/everest-expedition/" data-wow-duration="4s"><i class="fas fa-arrow-right"></i>Learn More </a>
        <!-- <a href="https://thimalayanepal.com/post/everest-expedition/" class="button__circle wow fadeInDown discover" data-wow-duration="3s" ><i class="fas fa-arrow-down"></i>Learn More </a> -->
        <!-- <a href="" class="button__circle" data-wow-duration="3s" ><i class="fas fa-arrow-down"></i>Learn More </a> -->
    </div>
</div>
</header> {% endcomment %}
<!-- Featured posts-->
<section class="service">
    <div class="container">
        {% comment %} <div class="title-left text-left wow bounce" data-wow-duration='2s' >
	    <h2>Our most sold <br> Packages</h2>
        </div> {% endcomment %}
        <div class="row wow bounce" data-wow-duration='2s'>
            <!--slide-->
            <div class="owl-carousel">
                {% for post in featured_posts %}
                <a href="{{ post.get_absolute_url }}">
                <div class="col">
                    <!--box card -->
                    <div class="box-card">
                        <!--overlay-->
                        <div class="overlay"></div>
                        <!--img card -->
                        <img class="img-card mb-4" src="{% if post.image %}{{ post.image.url }}{% endif %}">
                        <!--header card -->
                        <h3>{{ post.name }}</h3>
                    </div>
                </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<!--social work -->
<section class="social">
    <div class="container social-background">
        <div class="title-left text-left wow bounce" data-wow-duration='2s' >
            <h2>Our social <br> work</h2>
        </div>
        <!--row not reserve-->
        <div class="row">
            <!--img social -->
            <div class="col-md-6 text-center">
                <!--img-->
                <a href="{% url 'blog:socials' %}" data-wow-duration="4s">
                <img class="social__img" src="{% static 'img/social-work1.JPG' %}">
                </a>
            </div>
            <!--card info-->
            <div class="col-md-6 ">
                <!--card box -->
                <div class="info__social d-flex justify-content-center align-items-start flex-column w-100">
                    <!--title-->
                    <h3 class="head__social wow fadeInDown" data-wow-duration="2s" >Himalaya treks nepal always focus on making better future for those who are willing of and capable of.</h3>
                    <!--parg -->
                    <p class="parg__social text-justify wow fadeInDown" data-wow-duration="3s" >Our company always spend on 20% of profit for social work mainly we focus on education sector of remote area of nepal.</p>
                    <!--button-->
                    {% comment %} <a class="button__circle wow fadeInDown card-link" href="{% url 'blog:socials' %}" data-wow-duration="4s"><i class="fas fa-arrow-right"></i>Learn More </a> {% endcomment %}
                </div>
            </div>
        </div>
        <!--row reserve -->
        <div class="row">
            <!--row reserve class order-md-1 -->
            <!--img social -->
            <div class="col-md-6 text-center order-md-1 ">
                <!--img-->
                <a href="{% url 'blog:socials' %}" data-wow-duration="4s">
                <img class="social__img" src="{% static 'img/social-work2.JPG' %}">
                </a>
            </div>
            <!--card info-->
            <div class="col-md-6  ">
                <!--card box -->
                <div class="info__social d-flex justify-content-center align-items-start flex-column w-100">
                    <!--parg -->
                    <p class="parg__social text-justify wow fadeInDown" data-wow-duration="3s" >We are able to primary schools for dolkha jhesphu which is remote area of dolakha. We provide dress and books for those school who are excellent on education and low at income to encourage their education so due of money they don’t have to give up their education. At future our goal is to make nepal fully educated country in which we have send our proposals to government also.</p>
                    <!--button-->
                    {% comment %} <a class="button__circle wow fadeInDown card-link" href="{% url 'blog:socials' %}" data-wow-duration="4s"><i class="fas fa-arrow-right"></i>Learn More </a> {% endcomment %}
                </div>
            </div>
        </div>
        <div class="row">
            <!--img social -->
            <div class="col-md-6 text-center">
                <!--img-->
                <a href="{% url 'blog:socials' %}" data-wow-duration="4s">
                <img class="social__img" src="{% static 'img/social-work3.JPG' %}">
                </a>
            </div>
            <!--card info-->
            <div class="col-md-6 ">
                <!--card box -->
                <div class="info__social d-flex justify-content-center align-items-start flex-column w-100">
                    <!--parg -->
                    <p class="parg__social text-justify wow fadeInDown mt-3" data-wow-duration="3s" >
                        At pandemic COVIT 19 we deliver food to some of family who are unable to work and have zero income.<br>
                        At dolkha we built a house for widow who lost her everything on earthquake of 2015.<br>
                        Our goal is to provide food, shelter and home through our social work and mainly on education sector.<br>
                        We kindly request to our costumers if you agree with our goal we request you to donate some of amount happily.</p>
                    <!--button-->
                    {% comment %} <a class="button__circle wow fadeInDown card-link" href="{% url 'blog:socials' %}" data-wow-duration="4s"><i class="fas fa-arrow-right"></i>Learn More </a> {% endcomment %}
                </div>
            </div>
        </div>
</section>

<!--background -->
<!--img and the img src is in style html -->
<section class="background__advert" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)) , url({% static 'img/background.jpg' %})">
    <div class="card__advert d-flex justify-content-between align-items-center flex-wrap align-content-center">
        <!--title-->
        <h3 class="header__advert wow fadeInDown" data-wow-duration="4s" >Achieve Your</h3>
        <!--img-->
        <img class="img-advert wow bounce center" data-wow-duration='4s' src="{% static 'img/logo.png' %}">
        <!--title -->
        <h3 class="header__advert wow fadeInDown" data-wow-duration="4s">New Possible</h3>
    </div>
</section>
<!--instagram -->
<section class="service">
        <div class="title-left text-left wow bounce" data-wow-duration='2s'>
            <h2>Latest on Instagram</h2>
        </div>
        <script src="https://apps.elfsight.com/p/platform.js" defer></script>
        <div class="elfsight-app-64dc586a-08d2-40ba-bd82-c3790f030fdc"></div>
</section>

{% endblock %}